### ISSUE TITLE
Conectar Con Shared Server los GET

### ISSUE THREAD

**Issue by jontierno** [Tinder2Team/Tinder-Server#11]
Hay que hacer las clases que manejen la conexión con el shared server

**Comment by luraschi8** [comment]
Se decidió usar las libs Json.cpp y libcurl para integrar la funcionalidad.

**Comment by luraschi8** [comment]
Trabajando en el brach iss11

**Comment by luraschi8** [comment]
Completados los GET de la api. Faltan las location y los interest que todavía no están listos en el shared server. Esperando a @chelinho139 

Para los POST y UPDATE se  crea un nuevo issue.

**Comment by luraschi8** [comment]
Siguen faltando solo los intereses. Esperando a @chelinho139

**Comment by luraschi8** [comment]
Todos los get implantados.
