### ISSUE TITLE
Servicio de Match

### ISSUE THREAD

**Issue by luraschi8** [Tinder2Team/Tinder-Server#15]
En caso de que el usuario esté interesado en el candidato, el servidor deberá almacenar este interés para que en caso de que el candidato esté interesado, estos se puedan poner en contacto.

**Comment by jontierno** [comment]
No será mejor pasarla a la segunda entrega? Uciel no está pudiendo buildear el proyecto usando el 14.10

**Comment by urodriguez** [comment]
Bueno, no hubo caso. Libere el issue. Sigo con la idea original de trabajar sobre Android

**Comment by urodriguez** [comment]
Ya tome varios issues en el Client

**Comment by luraschi8** [comment]
trabajando en el branch iss15

**Comment by luraschi8** [comment]
Merged in https://github.com/Tinder2Team/Tinder-Server/commit/e35fd35764f8232454fd2d7403f9fe5fa42b7eef
