### ISSUE TITLE
Api de búsqueda de candidatos

### ISSUE THREAD

**Issue by jontierno** [Tinder2Team/Tinder-Server#39]
Linkeado con #25. Hay que proveer la funcionalidad para consultar los candidatos diarios.

**Comment by luraschi8** [comment]
Trabajando en el branch https://github.com/Tinder2Team/Tinder-Server/tree/iss39

**Comment by jontierno** [comment]
@luraschi8 Che, paso para acá lo de consultar un user que ya está matcheado. Tiene que estar en esta parte de la api. En profile no puedo ponerla, hay un problema, asi que tiene que ir en el resource de match
